name: RUST CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Step 3 - Run cargo check
        run: cargo check

  fmt:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable

      - name: Step 3 - Run cargo fmt
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable

      - name: Step 3 - Run cargo clippy
        run: cargo clippy
