name: RUST CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Step 3 - Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Step 3 - Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: rustfmt

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Step 3 - Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
