name: RUST CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Step 3 - Run cargo check
        run: mv .env.example .env && cargo check

  fmt:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Step 3 - Run cargo fmt
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Step 3 - Run cargo clippy
        run: mv .env.example .env && cargo clippy

  create-bin:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Step 3 - Run cargo build
        run: cargo build --release
      
      - name: Step 4 - Publish binary as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: starkwhale_alert
          path: target/release/starkwhale_alert